<?php

namespace Cadastro\Repository;

/**
 * RemedioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RemedioRepository extends \Doctrine\ORM\EntityRepository
{
}
