<?php
/**
 * This file generated by Zend\Expressive\Tooling\Factory\ConfigInjector.
 *
 * Modifications should be kept at a minimum, and restricted to adding or
 * removing factory definitions; other dependency types may be overwritten
 * when regenerating this file via zend-expressive-tooling commands.
 */
 
declare(strict_types=1);

return [
    'dependencies' => [
        'factories' => [
            Auth\teste\testeHandler::class => Auth\teste\testeHandlerFactory::class,
            Cadastro\Cliente\InserirHandler::class => Cadastro\Cliente\InserirHandlerFactory::class,
            Teste\HelloWorld\IndexHandler::class => Teste\HelloWorld\IndexHandlerFactory::class,
        ],
    ],
];
