<?php
/**
 * This file generated by Zend\Expressive\Tooling\Factory\ConfigInjector.
 *
 * Modifications should be kept at a minimum, and restricted to adding or
 * removing factory definitions; other dependency types may be overwritten
 * when regenerating this file via zend-expressive-tooling commands.
 */
 
declare(strict_types=1);

return [
    'dependencies' => [
        'factories' => [
            Cadastro\Handler\Cliente\DeletarHandler::class => Cadastro\Handler\Cliente\DeletarHandlerFactory::class,
            Cadastro\Handler\Cliente\EditarHandler::class => Cadastro\Handler\Cliente\EditarHandlerFactory::class,
            Cadastro\Handler\Cliente\InserirHandler::class => Cadastro\Handler\Cliente\InserirHandlerFactory::class,
            Cadastro\Handler\Cliente\ListarHandler::class => Cadastro\Handler\Cliente\ListarHandlerFactory::class,
            Cadastro\Handler\Usuario\DeletarHandler::class => Cadastro\Handler\Usuario\DeletarHandlerFactory::class,
            Cadastro\Handler\Usuario\EditarHandler::class => Cadastro\Handler\Usuario\EditarHandlerFactory::class,
            Cadastro\Handler\Usuario\InserirHandler::class => Cadastro\Handler\Usuario\InserirHandlerFactory::class,
            Cadastro\Handler\Usuario\ListarHandler::class => Cadastro\Handler\Usuario\ListarHandlerFactory::class,
        ],
    ],
];
